In [1]:
import pandas as pd
import xlrd

from pathlib import Path
from IPython.display import display
from tabula import read_pdf

<div class="alert alert-block alert-info">
    In diesem Notebook werden die einzelnen Datenbanken lediglich eingelesen und dargestellt, um einen Überblick über die vorhandenen Attribute zu geben
</div>

<div class="alert alert-block alert-warning">
    Setzen des Ordners für unbehandelte Datenbanken und anzeigen aller Dateien:
</div>

In [2]:
# ------------------- Pfad einstellen -----------------------

pfad = Path.cwd().parent / "1_Data-Acquisition-Wrapper/Gesammelte Datenbanken"

print(pfad)
print()

# ------------------ Print für Dateien -------------------

dateien = list(pfad.iterdir())

for datei in pfad.iterdir():
    if datei.is_file():
        print(datei.name)

C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\Gesammelte Datenbanken

CAES2014GeothermalData.xls
NOAA_NCEI_US_hot_springs_1978-1985.tab
REFLECT_Horizon_2020-Data_Export_2025-11-05_20-59-36.xlsx
thermal_springs_alps_with_HF_estimates.csv
water-1507814-supplementary.pdf
~$REFLECT_Horizon_2020-Data_Export_2025-11-05_20-59-36.xlsx

<div class="alert alert-block alert-warning">
    https://doi.pangaea.de/10.1594/PANGAEA.916088#:~:text=DGS,UNMIG%29.%20Italy.%20%28ht <br><br>
    DATENBANK 1: Thermal Springs Alps
</div>

In [7]:
# -------------------------- Pfad zur Datei ------------------
dateipfad = pfad / "thermal_springs_alps_with_HF_estimates.csv"

# -------------------------- Einlesen ------------------------
df = pd.read_csv(dateipfad)

display(df)

df.to_excel("daten.xlsx", index=False)

,spring number,spring location,spring name,longitude,latitude,type,well_depth_(m),flow_rate_mean_(m^3_s^-1),flow_rate_min_(m^3_s^-1),flow_rate_max_(m^3_s^-1),...,H_up_max_(W),Hv_net_best_(W),Hv_net_min_(W),Hv_net_max_(W),thermal_footprint_net_best_(m^2),thermal_footprint_net_min_(m^2),thermal_footprint_net_max_(m^2),thermal_radius_net_best_(m),thermal_radius_net_min_(m),thermal_radius_net_max_(m)
0,20,Euganei (Euganean geothermal area - Battaglia ...,Fonte Le Bibite,11.778856,45.284444,spring,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,31,Euganei (Euganean geothermal area - Cinto Euga...,Bagno Nord,11.649967,45.286944,spring,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,32,Euganei (Euganean geothermal area - Cinto Euga...,Bagno Sud,11.648300,45.285000,spring,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,33,Euganei (Euganean geothermal area - Cinto Euga...,Fattorelle,11.645522,45.295833,spring,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,45,Acqui (comment Jacek: general area?),23,8.453005,44.691677,springs and shallow wells,NaN,0.0162,NaN,NaN,...,NaN,37108.287,74216.574,0.0,4.166357e+07,4.055698e+07,4.277016e+07,3641.692756,3593.005351,3689.737769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,942,Perkova pušča - Karavanke,NaN,14.599200,46.423500,spring,NaN,0.0009,NaN,NaN,...,NaN,5350.374,10700.748,0.0,1.567522e+05,0.000000e+00,3.247385e+05,223.373632,0.000000,321.508107
307,943,Črna Kamniško-Savinjske Alps,NaN,14.645600,46.419300,spring,NaN,0.0099,NaN,NaN,...,NaN,78860.628,157721.256,0.0,9.345171e+05,0.000000e+00,3.572123e+06,545.404457,0.000000,1066.321759
308,944,Rogovilc - Kamniško-Savinjske Alps,NaN,14.712800,46.396200,spring,NaN,0.0013,NaN,NaN,...,NaN,11260.899,22521.798,0.0,1.251048e+05,0.000000e+00,5.048278e+05,199.554761,0.000000,400.863662
309,945,Kamniška Bistrica - Kamniško-Savinjske Alps,NaN,14.606100,46.311400,spring,NaN,0.2160,NaN,NaN,...,NaN,2035261.080,4070522.160,0.0,0.000000e+00,0.000000e+00,6.516226e+07,0.000000,0.000000,4554.315691
310,948,Bad Weissee,56,11.741089,47.759094,spring,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-block alert-warning">
    https://tudatalib.ulb.tu-darmstadt.de/items/9aca68d5-0c0c-4b93-bfe7-68269c0bd4cb <br><br>
    DATENBANK 2: Komplette REFLECT Datenbank
</div>

In [4]:
# -------------------------- Pfad zur Datei ------------------
dateipfad = pfad / "REFLECT_Horizon_2020-Data_Export_2025-11-05_20-59-36.xlsx"

# -------------------------- Einlesen ------------------------
df = pd.read_excel(dateipfad)

display(df)

,fluid_sample_id,well_id,local_id_f,latitude_,longitude_,country,powpl_name,nuts2_name,nuts3_name,date_of_well_completion_year,...,tritium_3h_thousandths,oxigen_18_so4_thousandths,sulfur_34_so4_thousandths,sulfur_34_h2s_thousandths,carbon_13_co2_thousandths,lithium_7_thousandths,boron_11_thousandths,strontium_87sr_per_86sr_thousandths,references_for_fluid_data,remarks_fluid
0,W_AU_001_FS_001,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Analysis GFZ laboratory,N/D
1,W_AU_001_FS_002,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Analysis GFZ laboratory,N/D
2,W_AU_001_FS_003,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Analysis GFZ laboratory,N/D
3,W_AU_001_FS_004,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Hydroisotop GmbH 347619,N/D
4,W_AU_001_FS_005,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Hydroisotop GmbH 347620,N/D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5100,N/D,W_IT_378,MOLINETTO,43.203889,10.856667,Italy,N/D,Toscana,Pisa,1970,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D
5101,N/D,W_IT_379,MOLINETTO 002,43.204167,10.847778,Italy,N/D,Toscana,Pisa,1975,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D
5102,N/D,W_IT_380,MONTEROTONDO 018,43.161111,10.855000,Italy,N/D,Toscana,Pisa,1964,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D
5103,N/D,W_IT_381,NOCCIOLO,43.203333,10.806111,Italy,N/D,Toscana,Pisa,1938,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D
5104,N/D,W_IT_382,OLIVETA,43.201389,10.806944,Italy,N/D,Toscana,Pisa,1939,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D

<div class="alert alert-block alert-warning">
    https://doi.pangaea.de/10.1594/PANGAEA.981233<br><br>
    DATENBANK 3: PANGEA Hotsprings USA
</div>

In [5]:
# -------------------------- Pfad ---------------------------
dateipfad = pfad / "NOAA_NCEI_US_hot_springs_1978-1985.tab"

# -------------------------- Kommentarende suchen ------------
skip = 0
with open(dateipfad, encoding="latin1") as f:
    for i, line in enumerate(f):
        if line.strip().startswith("*/"):
            skip = i + 1   # +1, damit wir ab der nächsten Zeile (also nach */) starten
            break

print(f"→ Überspringe {skip} Kommentarzeilen (bis einschließlich */)")


# -------------------------- Einlesen ------------------------
df = pd.read_csv(
    dateipfad,
    sep="\t",
    encoding="latin1",
    skiprows=skip,
    engine="python"
)


# -------------------------- Ausgabe -------------------------
display(df.head(10))
print(f"\nZeilen: {len(df)},  Spalten: {len(df.columns)}")

→ Überspringe 38 Kommentarzeilen (bis einschließlich */)

,State (State code),Latitude,Longitude,Name (Popular or USGS Spring Name),"Orig val (Temperature, water [Â°F])",Temp [Â°C],"Temp descr (B = boiling, H = hot, W = warm)",ID (P.P. 492 number from U.S. Geo...),ID (Circ. 790 number from US. Geo...),"ID (NOAA number on 1:250,000-scal...)",Map sheet (Standard U.S. Geological Surv...),Map sheet (Standard U.S. Geological Surv...).1
0,AK,55.983,-131.661,BAILEY HOT SPRING,198.0,92.0,NaN,76.0,27.0,1,KETCHIKAN,KETCHIKAN (D-5) 15
1,AK,57.085,-134.839,BARANOF WARM SPRINGS,124.0,51.0,NaN,69.0,NaN,1,SITKA,SITKA (A-3) 15
2,AK,56.680,-131.882,BARNES LAKE HOT SPRINGS,79.0,26.0,NaN,NaN,NaN,1,BRADFIELD CANAL,(BRADFIELD CANAL (C-6) 15)
3,AK,55.933,-131.559,BELL ISLAND HOT SPRINGS,165.0,74.0,NaN,79.0,28.0,2,KETCHIKAN,KETCHIKAN (D-5) 15
4,AK,56.233,-131.267,BRADFIELD CANAL HOT SPRINGS,135.0,57.0,NaN,NaN,NaN,2,BRADFIELD CANAL,(BRADFIELD CANAL (A-4) 15)
5,AK,65.053,-146.057,CHENA HOT SPRINGS,153.0,67.0,NaN,18.0,14.0,1,CIRCLE,CIRCLE (A-5) 15
6,AK,56.717,-132.005,CHIEF SHAKES HOT SPRINGS,122.0,50.0,NaN,73.0,26.0,1,PETERSBURG,(PETERSBURG (C-1) 15)
7,AK,52.840,-169.900,CHUGINADAK HOT SPRINGS,NaN,NaN,H,39.0,NaN,2,SAMALGA ISLAND,NaN
8,AK,65.483,-144.637,CIRCLE HOT SPRINGS,135.0,57.0,NaN,19.0,15.0,1,CIRCLE,CIRCLE (B-2) 15
9,AK,64.850,-162.300,CLEAR CREEK HOT SPRINGS,149.0,65.0,NaN,NaN,5.0,1,SOLOMON,(SOLOMON (D-1) 15)

Zeilen: 1661,  Spalten: 12

<div class="alert alert-block alert-warning">
    https://gdr.openei.org/submissions/425<br><br>
    DATENBANK 4: GDR CAES2015GeothermalData
</div>

In [6]:
# ---------------- Pfad zur Datei ----------------
dateipfad = pfad / "CAES2014GeothermalData.xls"

# ---------------- Einlesen ----------------------
df = pd.read_excel(dateipfad)

# ---------------- Ausgabe -----------------------
display(df)

,AnalysisURI,AnalysisName,Notes,SamplingFeatureName,SamplingFeatureURI,SamplingFeatureType,OtherSiteID,SpecimenID,Label,SpecimenDescription,...,TotalRa_pCiL,Tritium_TU,U_activity_pCiL,U_mgL.1,analyte,result,units,uncertainty,qualifier,measurementMethod
0,http://resources.usgin.org/uri-gin/doe/thermal...,Heise Hot Springs,NaN,Heise Hot Springs,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:320|usgsSiteID:433834111412401,CAES20140310_01,Heise,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,http://resources.usgin.org/uri-gin/doe/thermal...,Lidy Hot Springs 1,NaN,Lidy Hot Springs 1,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:612|usgsSiteID:440832112331001,CAES20140311_01,Lidy_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,http://resources.usgin.org/uri-gin/doe/thermal...,Lidy Hot Springs 2,NaN,Lidy Hot Springs 2,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:736|usgsSiteID:440843112331401,CAES20140311_02,Lidy_2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,http://resources.usgin.org/uri-gin/doe/thermal...,Green Canyon Hot Springs,NaN,Green Canyon Hot Springs,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:391|usgsSiteID:434729111260801,CAES20140311_03,Green Canyon,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,http://resources.usgin.org/uri-gin/doe/well/CA...,Sturm Well,NaN,Sturm Well,http://resources.usgin.org/uri-gin/idwr/well_2...,Well,API:11-043-30016,CAES20140311_04,Sturm,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,http://resources.usgin.org/uri-gin/doe/thermal...,Condie Hot Springs,NaN,Condie Hot Springs,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:116|usgsSiteID:431958113545801,CAES20140312_01,Condie,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,http://resources.usgin.org/uri-gin/doe/well/CA...,Greenhouse Well,NaN,Greenhouse Well,missing,Well,NaN,CAES20140312_02,Greenhouse,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,http://resources.usgin.org/uri-gin/doe/well/CA...,Eckart Office Well,NaN,Eckart Office Well,missing,Well,NaN,CAES20140313_01,Eckart,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,http://resources.usgin.org/uri-gin/doe/well/CA...,Campbell 1,NaN,Campbell 1,missing,Well,NaN,CAES20140313_02,Campbell_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,http://resources.usgin.org/uri-gin/doe/well/CA...,Campbell 2,NaN,Campbell 2,missing,Well,NaN,CAES20140313_03,Campbell_2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,http://resources.usgin.org/uri-gin/doe/thermal...,Miracle Hot Springs,NaN,Miracle Hot Springs,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:573|usgsSiteID:424131114513201,CAES20140313_04,Miracle,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,http://resources.usgin.org/uri-gin/doe/well/CA...,Driscoll Well,Unsure on drilled depth; there is a well very ...,Driscoll Well,missing,Well,NaN,CAES20140313_05,Driscoll_W,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,http://resources.usgin.org/uri-gin/doe/thermal...,Driscoll Spring,NaN,Driscoll Spring,missing,Thermal Spring,NaN,CAES20140313_06,Driscoll_S,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,http://resources.usgin.org/uri-gin/doe/well/CA...,CSI Well 2,NaN,CSI Well 2,http://resources.usgin.org/uri-gin/idwr/well_2...,Well,API:11-083-30002,CAES20140314_01,CSI_2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,http://resources.usgin.org/uri-gin/doe/well/CA...,Comore Loma 6,NaN,Comore Loma 6,missing,Well,NaN,CAES20140606_01,Conmore_6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,http://resources.usgin.org/uri-gin/doe/well/CA...,Comore Loma 5,NaN,Comore Loma 5,missing,Well,NaN,CAES20140606_02,Conmore_5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,http://resources.usgin.org/uri-gin/doe/well/CA...,Blackhawk 2,NaN,Blackhawk 2,missing,Well,NaN,CAES20140606_03,Blackhawk_2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,http://resources.usgin.org/uri-gin/doe/well/CA...,Blackhawk 1,NaN,Blackhawk 1,missing,Well,NaN,CAES20140606_04,Blackhawk_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,http://resources.usgin.org/uri-gin/doe/thermal...,Heise Hot Springs,NaN,Heise Hot Springs,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,NaN,CAES20140609_01,Heise,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,http://resources.usgin.org/uri-gin/doe/borehol...,Raft River Geothermal 1,NaN,Raft River Geothermal 1,http://resources.usgin.org/uri-gin/idwr/well_2...,Borehole,api:11-031-30001,CAES20140611_01,RRG1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,http://resources.usgin.org/uri-gin/doe/borehol...,Raft River Geothermal 2,NaN,Raft River Geothermal 2,http://resources.usgin.org/uri-gin/idwr/well_2...,Borehole,api:11-031-30002,CAES20140611_02,RRG2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,http://resources.usgin.org/uri-gin/doe/borehol...,Raft River Geothermal 7,NaN,Raft River Geothermal 7,http://resources.usgin.org/uri-gin/idwr/well_2...,Borehole,api:11-031-30007,CAES20140611_03,RRG7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,http://resources.usgin.org/uri-gin/doe/borehol...,Raft River Geothermal 4,NaN,Raft River Geothermal 4,http://resources.usgin.org/uri-gin/idwr/well_2...,Borehole,api:11-031-30004,CAES20140611_04,RRG4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,http://resources.usgin.org/uri-gin/doe/thermal...,Indian Hot Springs,NaN,Indian Hot Springs,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:591,CAES20140617_01,Indian,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,http://resources.usgin.org/uri-gin/doe/well/CA...,Grush Dairy,NaN,Grush Dairy,http://resources.usgin.org/uri-gin/idwr/well/I...,Well,IDWR Well ID: 312085 | GeoWellID: 3211,CAES20140618_01,Grush,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,http://resources.usgin.org/uri-gin/doe/well/CA...,Raft River USGS Well,NaN,Raft River USGS Well,missing,Well,NaN,CAES20140618_02,Raft_USGS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,http://resources.usgin.org/uri-gin/doe/well/CA...,Raft River Frasier Well,"Has been called Schmidt well, BLM well, Bridge...",Raft River Frasier Well,http://resources.usgin.org/uri-gin/idwr/well/I...,Well,GeoWellID: 1045 | USGSID:420628113232701,CAES20140618_03,Frasier,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,http://resources.usgin.org/uri-gin/doe/well/CA...,Raft River Crook Well,Has been called Crank well,Raft River Crook Well,http://resources.usgin.org/uri-gin/idwr/well/I...,Well,IDWR Well ID: 424365 | GeoWellID: 1038 | USGSI...,CAES20140618_04,Crook,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,http://resources.usgin.org/uri-gin/doe/thermal...,Milford Sweat,NaN,Milford Sweat,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:117|usgsSiteID:432158113464701,CAES20140623_01,Milford_Sweat,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,http://resources.usgin.org/uri-gin/doe/thermal...,Magic Hot Springs Landing Runoff,NaN,Magic Hot Springs Landing Runoff,missing,Thermal Spring,NaN,CAES20140623_02,Magic_Runoff,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,http://resources.usgin.org/uri-gin/doe/thermal...,Elk Creek 1,NaN,Elk Creek 1,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:99,CAES20140623_03,Elk_Creek_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,http://resources.usgin.org/uri-gin/doe/thermal...,Elk Creek 2,NaN,Elk Creek 2,ttp://resources.usgin.org/uri-gin/idwr/thermal...,Thermal Spring,IDWR:98|usgsSiteID:432524114373701,CAES20140623_04,Elk_Creek_2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,http://resources.usgin.org/uri-gin/doe/well/CA...,Barron Well,NaN,Barron Well,missing,Well,NaN,CAES20140624_01,Barron,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,http://resources.usgin.org/uri-gin/doe/thermal...,Wardrop Hot Springs (Gonzales' House),NaN,Wardrop Hot Springs (Gonzales' House),http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:94|usgsSiteID:432259114555301,CAES20140624_02,Wardrop,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,http://resources.usgin.org/uri-gin/doe/well/CA...,Magic Hot Springs Landing Well,NaN,Magic Hot Springs Landing Well,missing,Well,NaN,CAES20140624_03,Magic_Spring,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,http://resources.usgin.org/uri-gin/doe/thermal...,Prince Albert Hot Springs,also called Coyote Hot Springs,Prince Albert Hot Springs,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:272,CAES20140624_04,Prince_Albert,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,http://resources.usgin.org/uri-gin/doe/thermal...,Oakley Warm Spring,NaN,Oakley Warm Spring,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:894|usgsSiteID:421022113513901,CAES20140625_01,Oakley,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,http://resources.usgin.org/uri-gin/doe/well/CA...,Richard Austin Well 1,also Oakley Canal Co. Well 2 and Morris Mitche...,Richard Austin Well 1,ttp://resources.usgin.org/uri-gin/idwr/well/ID...,Well,IDWR Well ID: 402400 | GeoWellID: 925,CAES20140625_02,Austin_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,http://resources.usgin.org/uri-gin/doe/well/CA...,Marsh Creek Well,Also called Skaggs Ranch Well,Marsh Creek Well,http://resources.usgin.org/uri-gin/idwr/well/I...,Well,IDWR Well ID: 368342 | GeoWellID: 1154 | USGSI...,CAES20140625_03,Marsh_Creek_Well,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,http://resources.usgin.org/uri-gin/doe/thermal...,1000 Springs (Sliger's Well),also called Salmon Falls Creek Hot Springs,1000 Springs (Sliger's Well),http://resources.usgin.org/uri-gin/idwr/therma...,Well,IDWR:564,CAES20140626_01,Sliger,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,http://resources.usgin.org/uri-gin/doe/thermal...,Banbury Hot Springs Well,NaN,Banbury Hot Springs Well,missing,Well,NaN,CAES20140626_02,Banbury_Well,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,http://resources.usgin.org/uri-gin/doe/thermal...,Banbury Hot Springs,NaN,Banbury Hot Springs,http://resources.usgin.org/uri-gin/idwr/therma...,Thermal Spring,IDWR:580,CAES20140626_03,Banbury_Spring,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-block alert-warning">
    https://www.mdpi.com/1437152<br><br>
    DATENBANK 5: Hydrochemical Characteristics of Earthquake-Related Thermal Springs along the Weixi–Qiaohou Fault
</div>